### ISSUE TITLE
Other changes

### ISSUE THREAD

**Issue by Sagarjit** [cleonixtechnologies/IndoJapan#3]
1. There will be 3 dorpdown menu under about us-
   Company Overview
   Our Team
   Mission, Vision, Value & Goals
2. Remove Vertical LED from products
3. Please put the below content in COB & High power LED page
   "To be launched in the month of March"
4. Please change the old logo with new font.
5. Remove "inner cores" from 4th business goals box In index page.
6. Correct the space & comma in 3rd core values box In index page.

**Comment by i-puspita** [comment]
please provide the old logo

**Comment by Sagarjit** [comment]
![ijh brand](https://cloud.githubusercontent.com/assets/16955810/12884100/0c14d2b6-ce82-11e5-914a-cc074b231229.png)

**Comment by i-puspita** [comment]
updated
