### ISSUE TITLE
Changes in Website

### ISSUE THREAD

**Issue by Sagarjit** [cleonixtechnologies/IndoJapan#5]
1. In 4th banner put the caption in One line.
2. Add COB LED 30W, 40W, 50W. Images is attached. In description the content will be "To be launched in the month of March"
3. In home page under mission vision write "We are India's first LED CHIP manufacturer".
4. Remove the white spot from the logo.
5. In our skills change the 1st round color to Pink & make it 90%.
6. Contact us enquiry will go to both email ids.
7. Add mobile number in contact us- 9836462987
8. Remove "Private company" from contact us.
9. West Bengal Electronic Complex will be replaced with "WEBEL Electronic Complex" in contact us.
10. SMD 2835- 
    28 will be 39 in 1st box
    70 will be 75 in 2nd box
    140 will be 150 in 3rd box.
11. Social media links- https://www.facebook.com/indojapanled/

https://twitter.com/IJHLEDtweet

**Comment by Sagarjit** [comment]
![cob](https://cloud.githubusercontent.com/assets/16955810/12910555/a8dc444e-cf31-11e5-9105-831efb0b9a64.jpg)

**Comment by i-puspita** [comment]
image is not loading

**Comment by Sagarjit** [comment]
Check mail

**Comment by i-puspita** [comment]
updated
